### ISSUE TITLE
Help wanted!

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-provider#1]
This will be a JavaScript library (written in TypeScript) that will give websites and web apps access to blockchain data.

There are many easy to implement functions that can be added to this provider, like query the indexer for blocks, transactions, and more.

**Comment by sondreb** [comment]
Consider using this sample repo as the basis for the provider: https://github.com/tomchen/example-typescript-package

**Comment by sondreb** [comment]
Here is an example from Web3.js:

```js
var Web3 = require('web3');
var provider = 'ADD_YOUR_ETHEREUM_NODE_URL';
var web3Provider = new Web3.providers.HttpProvider(provider);
var web3 = new Web3(web3Provider);
web3.eth.getBlockNumber().then((result) => {
  console.log("Latest Ethereum Block is ",result);
});
```

**Comment by GonzRodriguez** [comment]
Hi sondreb, 
I'm new to open source and I'd like to contribute to a project, how can I help?

**Comment by sondreb** [comment]
> Hi sondreb,
> I'm new to open source and I'd like to contribute to a project, how can I help?

Fantastic! First step would be to make an API wrapper in TypeScript that compiles to JavaScript and runs in both browser and Node.js.

This is the documentation for the API: https://city.indexer.blockcore.net/docs/index.html

Due to a bug in the documentation generated, it lists a lot more APIs than actually exists. It is only "Insight" and "Query" that are real APIs on this URL.

I'll setup the initial sample npm package I mentioned earlier, we'll use their mechanism for releasing, build, etc. to get started more quickly.

**Comment by sondreb** [comment]
I have updated the repo with the basic setup for npm. It might be daunting and there is a lot of files. It is also setup with Husky, which does commit tests and linting of your commit message.

The subject must include an type, which can be "build", "ci" and others.

And the subject must be lower-case characters only.

Example: `chore: add a basic template for npm package`

We'll leave the Husky on for now just to see if it's valuable.

**Comment by sondreb** [comment]
You basically clone the repo and get started coding inside the `src` folder: https://github.com/block-core/blockcore-provider/tree/main/src

I added some basic instructions in the top of the README, the other instructions might also be useful.

**Comment by GonzRodriguez** [comment]
Wow, thanks for all the effort and time! I'll read everything carefully in a minute and see how I can be useful. 

Sadly I have not as much time as I'd like to code, and there are a few thing that I never worked on, but I'll do my best to help out. 

I'll get back to you if I have any doubt.
